# Generated by Django 2.2.14 on 2022-06-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plname', models.CharField(max_length=100)),
                ('plnemail', models.EmailField(max_length=100)),
                ('plnmobile', models.CharField(max_length=10)),
                ('plnaddress', models.CharField(max_length=200)),
                ('plnprice', models.CharField(max_length=10000)),
                ('plnstatus', models.BooleanField()),
                ('plnbook', models.BooleanField()),
                ('plnusers', models.CharField(max_length=100)),
            ],
        ),
    ]
