# Generated by Django 2.2.14 on 2022-06-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societyAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plumber',
            name='plnemail',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='plumber',
            name='plnmobile',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
