# Generated by Django 2.2.14 on 2022-06-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societyAdmin', '0002_auto_20220605_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carpenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carname', models.CharField(max_length=100)),
                ('caremail', models.EmailField(max_length=100, unique=True)),
                ('carmobile', models.CharField(max_length=10, unique=True)),
                ('caraddress', models.CharField(max_length=200)),
                ('carprice', models.CharField(max_length=10000)),
                ('carstatus', models.BooleanField()),
                ('carbook', models.BooleanField()),
                ('carusers', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Electrician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elename', models.CharField(max_length=100)),
                ('eleemail', models.EmailField(max_length=100, unique=True)),
                ('elemobile', models.CharField(max_length=10, unique=True)),
                ('eleaddress', models.CharField(max_length=200)),
                ('eleprice', models.CharField(max_length=10000)),
                ('elestatus', models.BooleanField()),
                ('elebook', models.BooleanField()),
                ('eleusers', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Painter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('painame', models.CharField(max_length=100)),
                ('paiemail', models.EmailField(max_length=100, unique=True)),
                ('paimobile', models.CharField(max_length=10, unique=True)),
                ('paiaddress', models.CharField(max_length=200)),
                ('paiprice', models.CharField(max_length=10000)),
                ('paistatus', models.BooleanField()),
                ('paibook', models.BooleanField()),
                ('paiusers', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ruffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rufname', models.CharField(max_length=100)),
                ('rufemail', models.EmailField(max_length=100, unique=True)),
                ('rufmobile', models.CharField(max_length=10, unique=True)),
                ('rufaddress', models.CharField(max_length=200)),
                ('rufprice', models.CharField(max_length=10000)),
                ('rufstatus', models.BooleanField()),
                ('rufbook', models.BooleanField()),
                ('rufusers', models.CharField(max_length=100)),
            ],
        ),
    ]
