# Generated by Django 2.2.14 on 2022-06-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societyAdmin', '0003_carpenter_electrician_painter_ruffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='plumber',
            name='plntype',
            field=models.CharField(default='Plumber', max_length=100),
        ),
    ]
