# Generated by Django 2.2.14 on 2022-06-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societyAdmin', '0004_plumber_plntype'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpenter',
            name='cartype',
            field=models.CharField(default='Carpenter', max_length=100),
        ),
        migrations.AddField(
            model_name='electrician',
            name='eletype',
            field=models.CharField(default='Electrician', max_length=100),
        ),
        migrations.AddField(
            model_name='painter',
            name='paitype',
            field=models.CharField(default='Painter', max_length=100),
        ),
        migrations.AddField(
            model_name='ruffer',
            name='ruftype',
            field=models.CharField(default='Roofer', max_length=100),
        ),
    ]
