# Generated by Django 2.2.14 on 2022-06-06 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20220606_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='carpentersDetails',
        ),
    ]
