# Generated by Django 2.2.14 on 2022-06-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_carpentersdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='carpentersDetails',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='electricianDetails',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='painterDetails',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='plumberDetails',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='rooferDetails',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
