# Generated by Django 2.2.14 on 2022-06-06 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20220606_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='carpentersDetails',
        ),
        migrations.RemoveField(
            model_name='user',
            name='electricianDetails',
        ),
        migrations.RemoveField(
            model_name='user',
            name='painterDetails',
        ),
        migrations.RemoveField(
            model_name='user',
            name='plumberDetails',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rooferDetails',
        ),
    ]
